services:
  db:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    
    env_file:
      - ./backend/db.env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  backend:
    depends_on:
      db:
        condition: service_healthy
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"